[project]
name = "dast"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "asyncio>=4.0.0",
    "asyncssh>=2.21.1",
    "paramiko>=4.0.0",
    "scapy>=2.6.1",
    "termcolor>=3.2.0",
]
